// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel pixelCalc

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> textureOut;
RWStructuredBuffer<double> rect;
RWStructuredBuffer<float4> colors;

[numthreads(32,32,1)]
void pixelCalc(uint3 id : SV_DispatchThreadID)
{
    float k = 0.0009765625;
    double dx, dy;
    double p, q;
    double x, y, xNew, yNew, d = 0;
    uint itn = 0;
    
    dx = rect[2] - rect[0];
    dy = rect[3] - rect[1];
    p = rect[0] + ((int) id.x) * k * dx;
    q = rect[0] + ((int) id.y) * k * dy;

    x = p;
    y = q;
    
    while (itn < 255 && d < 4)
    {
        xNew = x * x - y * y + p;
        yNew = 2 * x * y + q;
        
        x = xNew;
        y = yNew;
        
        d = x * x + y * y;
        itn++;
    }
    
    textureOut[id.xy] = colors[itn];

}
